import Button from "@/components/atomics/Button";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Atomic Design at E-TICKET",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col w-[100%] h-[100vh] justify-start items-center pt-20">
        <Link href={"/"}>
          <Button text="GO TO HOME" />
        </Link>
        {children}
      </body>
    </html>
  );
}
